# Use Node.js as the base image
FROM node:lts-alpine3.20
# Set the working directory
WORKDIR /usr/src/app
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the rest of the application code
COPY . .
# Build the application
RUN npm run build
# Expose the port the app runs on
EXPOSE 3001
# Start the application
CMD ["npm", "run", "start:prod"]
